### ISSUE TITLE
Overall Batch Effect

### ISSUE THREAD

**Issue by mRcSchwering** [theislab/kBET#20]
Hi,

I wanted to use `kBET` to estimate the overall magnitude of batch effects in my data.
Does it make sense to use the difference between expected and observed mean rejection rate for this?
(`summary$kBET.observed[1] - summary$kBET.expected[1]`)

Best
Marc

**Comment by mbuttner** [comment]
Dear Marc,

we have been thinking about the comparison of observed and expected kBET results. The problem with taking the difference of expected and observed mean is that it may become negative. We have observed this phenomenon a couple of times already. 
For us, it is more natural to compute the likelihood-ratio of observed and expected results. We provide a p-value for the significance of the observed kBET result (`summary$kBET.signif[1]`). 
So in total, I suggest to use the observed mean rejection rate and evaluate it with its significance level.

Best,
Maren
