### ISSUE TITLE
kBET within known cluster

### ISSUE THREAD

**Issue by AlemuTA** [theislab/kBET#39]
Hi,

I appreciate the great work, kBET. I have a question about its implementation. All (simulated) setting in the paper show no clustering of cells. When cells are clustered, then kBET should only consider neighborhoods within clusters. Is there a way to force kBET to do so? 

Best regards,
Alemu

**Comment by mbuttner** [comment]
Hi Alemu, 

that's a great remark. You can subset your matrix and batch covariate to the respective cluster and iterate over the number of clusters in your data. We did that in the paper for the mouse embryonic development data (Fig. 4a-c), and we averaged over all kBET results. 

Here is a code snippet, which forces kBET to take only values from a predefined cluster.

```
#create experimental design with clusters
batch <- c(rep(1, 160), rep(seq_len(3)+1, each=80))
clusters <- sample(LETTERS[1:5], size = length(batch), replace=TRUE)

#visualise design
table(batch, clusters)

#create test data set
data <- matrix(rpois(n = 50000, lambda = 10)*rbinom(50000,1,prob=0.5), ncol=length(batch))

#test each cluster
kBET_result_list <- list()
sum_kBET <- 0
for (cluster_level in  unique(clusters)){
   batch_tmp <- batch[clusters == cluster_level]
   data_tmp <- data[,clusters == cluster_level]
   kBET_tmp <- kBET(df=data_tmp, batch=batch_tmp, plot=FALSE)
   kBET_result_list[[cluster_level]] <- kBET_tmp
   sum_kBET <- sum_kBET + kBET_tmp$summary$kBET.observed[1]
}

#averaging
mean_kBET = sum_kBET/length(unique(clusters))
```

**Comment by AlemuTA** [comment]
Thanks !
