### ISSUE TITLE
Seurat CCA

### ISSUE THREAD

**Issue by alextamburino** [theislab/kBET#41]
Hi,

I'm trying to use kBet for optimizing dims.use in Seurat CCA. Can you please provide a quick explanation/code for how you did this in Buttner et al?

Thanks,
Alex

**Comment by mbuttner** [comment]
Hi Alex,

We computed 10-15 dimensions (called CCs) in CCA. Originally, we wanted to be as consistent as possible and tried to compute 20 CCs (similar to the 20 PCs that we computed with PCA), but that did not work. We did not figure out a 'correct' number of CCs and as far as I understand the Seurat tutorial, the people from the Satija lab do not have a clear answer to that question as well. 
I have prepared a small code snippet for you to show how we tested Seurat's CCA results with kBET.

```
#prepare data (NormalizeData, FindVariableGenes, ScaleData from Seurat package)
#combine datasets (each is a Seurat object)
ob.list <- list(celseq, celseq2, fluidigmc1, smartseq2)

#define gene set
genes.use <- c()
for (i in 1:length(ob.list)) {
  genes.use <- c(genes.use, head(rownames(ob.list[[i]]@hvg.info), 1000))
}
genes.use <- names(which(table(genes.use) > 1))
for (i in 1:length(ob.list)) {
  genes.use <- genes.use[genes.use %in% rownames(ob.list[[i]]@scale.data)]
}

# Run multi-set CCA
x <- RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 10)
#Align
x <- AlignSubspace(x,
        reduction.type = "cca",
        grouping.var = "tech",
        dims.align = 1:10)
#run kBET
batch_test <- kBET(x@dr$cca.aligned@cell.embeddings, batch= x@meta.data$tech)
```

I hope that helps.

**Comment by alextamburino** [comment]
Thanks Maren!
