### ISSUE TITLE
weird(opposite) result

### ISSUE THREAD

**Issue by james20141606** [theislab/kBET#42]
Hi, I enjoy your tool very much! However, I encountered a weird problem dealing with a small sample size problem. I found that kBET may not be very stable when quantifying batch effect? I found that the score may be exactly 0 or 1 and the scores may be totally opposite to intuition and visualization. Is it possible kBET requires a big sample size to work?

**Comment by mbuttner** [comment]
Hi,
kBET is a stochastic approach, which leads to some variation in the results, but jumping from 0 to 1 and back was not among the results of my tests. However, kBET is not suited for 'small' dataset samples (where small means less than ~20 samples per batch). In this regime, the test statistic is not reliable. I do not know how small your dataset is, therefore, I can't be more specific.
