### ISSUE TITLE
kBET not working (?)

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [theislab/kBET#43]
Hi,

I have a data set with the following samples:

|Sample|Replicates|
|:------:|:---------:|
|Vehicle|3|
|Short term treatment|3|
|Long term treatment|3|

I subsampled my matrix to 1,000 cells, with 21,190 genes.

It looks like this:

```
mydata[c(1:5), c(1:10)]

GNAI3 CDC45 H19 SCML2 APOH NARF CAV2 KLF6 SCMH1 COX5A
231279535536556-V_1     0     0   0     0    0    0    1   22     0     5
226953411382694-V_1     1     0   0     0    0    0    0    3     0     1
196527716482341-V_1     0     0   0     0    0    1    0    0     0     4
160440043826078-V_1     0     0   0     0    0    0    0    3     0     1
232301289171748-V_1     1     0   0     0    0    0    2   12     3     3
```

However, when I run `kBET` and do `batch.estimate$summary`, I get:

```
      kBET.expected kBET.observed kBET.signif
mean              0             0           1
2.5%              0             0           1
50%               0             0           1
97.5%             0             0           1
```

All tests result in 0.

This, occurs both if I set each sample as a different batch, or if label each treatment as a different batch.

The example in the method's help however, does provide results different from zero:

```
      kBET.expected kBET.observed kBET.signif
mean     0.02653333        0.0212  0.73780060
2.5%     0.00000000        0.0000  0.01681108
50%      0.02666667        0.0000  1.00000000
97.5%    0.06666667        0.0800  1.00000000
```

Do you have any idea of why this could be happening?

Thank you,

**Comment by mbuttner** [comment]
Hi,

I assume that it has something to do with your batch covariate. Do you use `factor` as data type for the batch?

Best

**Comment by alejandro-jimenezsanchez** [comment]
Thanks so much! That was the solution.

`mybatch <- as.factor(mybatch)`

Thank you,
