### ISSUE TITLE
The input data format

### ISSUE THREAD

**Issue by nottwy** [theislab/kBET#44]
Sorry to disturb you but I have a problem about the input of kBET.
In the readme you write that columns represent features (genes) and let's assume it's true.

    #data: a matrix (rows: samples, columns: features (genes))
    #batch: vector or factor with batch label of each cell 
    batch.estimate <- kBET(data, batch)

In the example you prepared, you said:
    
    batch <- rep(seq_len(10),each=20)
    data <- matrix(rpois(n = 50000, lambda = 10)*rbinom(50000,1,prob=0.5), ncol=200)
    batch.estimate <- kBET(data,batch)

so the 'data' is a 250x200 matrix and there are 200 genes. And the 'batch' is a vector with 200 elements.

In my understanding, the batch information should be related about something like the experiment rather than genes. Am I correct? So the column represents cells and the row represents genes, it is true?

**Comment by mbuttner** [comment]
Hi,

thank you for the comment! 
You are correct, the batch information is related to the experiment (cells/samples) rather than genes. The correct example would be 
```
batch <- rep(seq_len(10),each=20)
data <- matrix(rpois(n = 50000, lambda = 10)*rbinom(50000,1,prob=0.5), nrow=length(batch))
batch.estimate <- kBET(data,batch)
```
However, kBET transposes any data matrix where rows and columns are swapped - which happens also in the current example.
