### ISSUE TITLE
cell x feature or feature x cell?

### ISSUE THREAD

**Issue by jon-xu** [theislab/kBET#48]
Hi,

I see you mentioned row for cell and column for features.

But in your example, there are 200 labels (for cells), while your sample data has 250 rows with 200 columns.

Does that mean we should put cells in columns, please?

Thanks!
Jon

**Comment by phoebee-h** [comment]
Hey Jon,
I just pass by, not an official answer. Someone has asked this before. See #44.
Hope this help.

**Comment by jon-xu** [comment]
Thanks Phoebee!

I’ll have a try.

Cheers,

Jon

**Comment by mbuttner** [comment]
Dear Jon,

kBET checks the input dimension of your data matrix and swaps the dimensions, if necessary. I'll see to correct my example.

Best,
Maren

**Comment by jon-xu** [comment]
Thanks Maren!

I’ve used and cited kBET in my paper.

Thanks for the tool!

Cheers,

Jon


在 2019年9月20日，16:37，Maren Büttner <notifications@github.com<mailto:notifications@github.com>> 写道：


Dear Jon,

kBET checks the input dimension of your data matrix and swaps the dimensions, if necessary. I'll see to correct my example.

Best,
Maren
