### ISSUE TITLE
High rejection rates in integrated data of lung and liver than two lung tissues

### ISSUE THREAD

**Issue by Quan-L** [theislab/kBET#50]
Hello there ,I used  the package to detect the batch effect of the data,for example
![image](https://user-images.githubusercontent.com/54166216/63146102-63fb0500-c02c-11e9-8eb8-427881c27008.png)

First, I used the Seurat to integrate the raw matrix, then fitered  cell  and caculated the  top  2000 VariableFeatures. I used the matrix of 2000 genes as the data to search the batch effect with the kBET, here are my results:

 **lung1-liver1:**

![lung1-liver_raw_factor big](https://user-images.githubusercontent.com/54166216/63146396-6578fd00-c02d-11e9-9f42-93158e009ee3.png)

**lung1-lung3**

![lung1-3raw big_factor](https://user-images.githubusercontent.com/54166216/63146482-ab35c580-c02d-11e9-98b6-8487e936cfb7.png)

Reasonable, the batch effect within different tissues is higher than within the same tissues. 
So,I want to know that why the rejection rates between two different tissues (lung1 vs liver1) lower than the same tissues (lung1 vs lung3).
I am looking forward to your reply. Thank you.

**Comment by mbuttner** [comment]
Hi Quan-L,

that's an interesting question and I agree on your reasoning. I have a couple of suggestions and questions:
1. Did you check the batch effects before correction?
2. Lung-Liver: Can you rule out overcorrection? I am wondering if lung and liver have enough cell types in common to ensure a reasonable data integration. If not, Seurat's data integration method would integrate completely distinct cell types. 
3. Lung1-Lung3: Do you observe several cell types and, if yes, shifts in the cell type composition? In that case I advise to run kBET per cluster (or cell type) and average over all kBET results to account for frequency shifts - I wrote an example in the README, section 'Subsampling'.
