### ISSUE TITLE
Seurat v3 and kBET

### ISSUE THREAD

**Issue by rmenafra** [theislab/kBET#52]
Hi everybody,
is there a vignette or a snippet explaining how to use kBET on Seurat V3 integration method (CCA + anchors https://doi.org/10.1016/j.cell.2019.05.031 ), if possible?
Thanks

**Comment by PrashINRA** [comment]
I was looking for the same but could not find it -
I tried using these codes, it ran successfully but the rejection rate was too high for my data. I am not sure if there is something wrong.
so_cca (## your Seurat object with CCA corrections)
library(kBET)
 ###get a matrix data from the so_cca
k_mtx <- GetAssayData(so_cca, slot = 'scale.data')

##Run kBET
batch.estimate <- kBET(k_mtx, batch, plot=FALSE)
plot.data <- data.frame(class=rep(c('observed', 'expected'), 
                                  each=length(batch.estimate$stats$kBET.observed)), 
                        data =  c(batch.estimate$stats$kBET.observed,
                                  batch.estimate$stats$kBET.expected))
gplot <- ggplot(plot.data, aes(class, data)) + geom_boxplot() + 
  labs(x='Test', y='Rejection rate',title='kBET on CCA') +
  theme_bw() +  
  scale_y_continuous(limits=c(0,1))

**Comment by mbuttner** [comment]
Hi rmenafra,

I looked into the problem with Seurat objects and proposed a solution on the similar issue #47 .

Best regards,
Maren
