### ISSUE TITLE
Warning from 'if  (class(knn) == "list")' in R 4.0.0

### ISSUE THREAD

**Issue by jernest1** [theislab/kBET#54]
In R 4.0.0 I am getting the following warning from the kBET function:
```
Warning messages:
1: In if (class(knn) == "list") { :
  the condition has length > 1 and only the first element will be used
2: In if (class(knn) == "list") { :
  the condition has length > 1 and only the first element will be used
3: In if (class(knn) == "list") { :
  the condition has length > 1 and only the first element will be used
```
It may have to do with the fact that R 4.0.0 assigns both class "matrix" and "array" to matrices. See the discussion here: https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html
They recommend using `if(is(object, "list"))` instead of `if(class(object) == "list")`.

**Comment by mbuttner** [comment]
Hi @jernest1 
thank you for pointing this out! I still use R-3.* and haven't tried R-4.*, but I look into it soon.

**Comment by el-behnam** [comment]
Hi. I am using R4.2.0 and now this warning is an error and the @jernest1 suggestion has solved my the problem. I just changed the line 195 in kBet.R file to fix it.

**Comment by mbuttner** [comment]
Hi @el-behnam 
Thank you for the update and the suggestion. I updated the class check in the `kBET.R` function to fix it.

**Comment by ajwilk** [comment]
I believe there was a small error introduced in this commit in `2e2b091` 
Should be: 
```if(is(knn, "list"))```

**Comment by mbuttner** [comment]
Thank you for pointing this out. My bad. I just fixed it.
