### ISSUE TITLE
Dose kBET allow normalized matrix as input?

### ISSUE THREAD

**Issue by yycunc** [theislab/kBET#56]
Hi there,

I used kBET to detect the batch effect of the data after batch effect correction. However, I have a question on the input format. The example shows that kBET function takes raw count matrix as the input. However, after correction using Seurat, I only have normalized and scaled matrices, where there would be both positive and negative values (as I showed below). So I wonder can I use the log-transformed data as the input file?

5 x 5 sparse Matrix of class "dgCMatrix"
                   F3_Unsorted_cell1 F3_LMPP_cell2 F3_LMPP_cell3 F3_MPP_cell4 F3_MPP_cell5
ENSMUSG00000027562       4.609797282    5.60968033   5.563666940   4.71301533  5.278862679
ENSMUSG00000027556       4.303335643    6.25554822   5.787379093   4.03904792  4.507551082
ENSMUSG00000027863       0.188618445    .           -0.011766633  -0.03955919 -0.005985704
ENSMUSG00000035042       0.157980256    0.03028318   0.194765506  -0.06541776 -0.007800523
ENSMUSG00000056399      -0.001272955   -0.02507969  -0.001600793  -0.04997392 -0.018655246

Thanks!

**Comment by mbuttner** [comment]
Hi @yycunc 
thank you for posting your issue and I am sorry for my late reply. To date, kBET accepts only input in the dense matrix format or a knn-graph in R. The sign of the matrix entries do not matter when we compute the nearest neighbours of each cell.
