### ISSUE TITLE
Can I apply pandas pd as input or np.matrix as input for kBET? Thanks.

### ISSUE THREAD

**Issue by ChineseBest** [theislab/kBET#60]

**Comment by mbuttner** [comment]
Hi @ChineseBest 
we currently do not provide a Python-version of kBET, but we implemented a Python wrapper in the [scIB package](https://github.com/theislab/scib). Here, we use `anndata` objects as input matrix, e.g.
```
import anndata as ann
import scIB
import pandas as pd

data = ann.read_csv('input_data.csv')
batch = pd.read_csv('batch.csv')
cell_type = pd.read_csv('cell_type.csv')

# add batch covariate
data.obs['batch'] = batch
# add cell type covariate
data.obs['cell_type'] = cell_type

#run kBET from scIB
kBET = scIB.metrics.kBET(adata = data, batch_key = 'batch', label_key='cell_type', type='full')
```

Note: If you don't have cell type information, replace the `cell_type` covariate by a vector of identical entries. The code snippet above is not tested.

**Comment by ChineseBest** [comment]
Thanks a lot. I use ryp2 to call the R function in python and get the result. I think the less distance between norm (ideal) reject rate and observed reject rate, the better my batch effect removal method will be. Is it correct? Thanks.

**Comment by mbuttner** [comment]
> Thanks a lot. I use ryp2 to call the R function in python and get the result. I think the less distance between norm (ideal) reject rate and observed reject rate, the better my batch effect removal method will be. Is it correct? Thanks.

Yes, that's correct. Great to hear it's working for you with `rpy2`.

**Comment by ChineseBest** [comment]
Thanks a lot.
