### ISSUE TITLE
Questions about cell type parameters.

### ISSUE THREAD

**Issue by ChineseBest** [theislab/kBET#61]
If I do not have cell type variables, when I call kBET(), can I leave this place as none or empty? Or I must fill something? Thanks.

In addition, sometimes I notice that the SOTA's rejection rate is higher than old method (such as seurat v3). Thanks.

**Comment by mbuttner** [comment]
Dear @ChineseBest ,

I am a bit at a loss about the question on cell type variables - can you specify the command you would like to call and which old results you are referring to? We have not changed the algorithm apart from minor adaptations to deal with NAs. 

In general, all you need to call `kBET()` is a data matrix and a variable that specifies the batch ID for each cell. 

Best,
Maren

**Comment by ChineseBest** [comment]
Hi, thanks for your reply. I mean can I also consider the cell type label for kBET method? For example, change batch information to cell type label information. Therefore, I think a lower kBET acceptance rate (based on cell type) means a better effect. Thanks

**Comment by mbuttner** [comment]
Hi,
yes, in theory that works. However, I do believe that there are some more suitable metrics to looks at to quantify the separation by cell type (e.g. silhouette score, adjusted rand index, normalised mutual information). We have implemented these and some others in the [scIB](https://github.com/theislab/scib/tree/master/scIB) package (in Python).
