### ISSUE TITLE
Scanpy Anndata object to KBET?

### ISSUE THREAD

**Issue by Lesdormis** [theislab/kBET#67]
Hi KBet developers,

I was wondering if you have guidance or tutorials on how to run KBET on Integrated scanpy Anndata object?

Maybe you have one already, but I cannot find it after searching.

Thanks!

**Comment by mbuttner** [comment]
Hi @Lesdormis 
thank you for your interest! We wrote a Python wrapper for kBET in the [scIB](https://github.com/theislab/scib) package in the `metrics` module. There is a brief description on the usage in the Readme file of `scIB` on how to run a metric implemented in `scIB`. 
I hope that helps!

**Comment by Lesdormis** [comment]
OK, great, thanks
