### ISSUE TITLE
is df input kBET a data frame with cells in rows and features in columns or the opposite?

### ISSUE THREAD

**Issue by joseale2310** [theislab/kBET#77]
In the documentation and help pages, the df option of kBET states:

```
dataset (rows: cells, columns: features)
```

However, when I am running the vignette, I find that the argument given to the kBET function is a matrix with features in rows and in columns the cells. 

Which one is the correct one?

Best,
Jose

**Comment by mbuttner** [comment]
Hi Jose,

thank you for pointing this out. KBET checks the length of the batch label and the shape of the matrix. It transposes the matrix if necessary.
Normally, cells should be in the rows.

**Comment by joseale2310** [comment]
Thanks! I guess the issue can be closed then. Could it be updated in the docs? It would be much clearer, thanks!

**Comment by mbuttner** [comment]
Thanks for the suggestion, I added a clarifying statement in the Readme file.
